# fly.toml app configuration file generated for revotext-meet-agent on 2026-05-15T23:52:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'revotext-meet-agent'
primary_region = 'iad'
kill_signal = 'SIGINT'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'rolling'

[env]
  WHISPER_COMPUTE = 'int8'
  WHISPER_MODE = 'local'
  WHISPER_MODEL = 'base.en'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048
